### ISSUE TITLE
[Feature] MemberCount

### ISSUE THREAD

**Issue by siltentassasin** [Arashiryuu/crap#118]
Hey, ist it possible to make in the MemberCount Plugin an option to disable the option include/exclude server in the server context menu? Because I have a lot of plugins and so my context menu is currently a lot chaotic and it helps me realy if it would be possible to disable this menu entry, because I enabled it anyway for all servers and don't want to exclude some.

**Comment by Arashiryuu** [comment]
could easily do that with some css
```css
#guild-context-membercount-toggle,
#guild-context-membercount-toggle + div[role="separator"] {
    display: none;
}
```
