### ISSUE TITLE
[Other] Change member count text color

### ISSUE THREAD

**Issue by AutumnClove** [Arashiryuu/crap#143]
I'm attempted to change the color of the member count on top of the member list, however, when editing this.css adding color to it does not result in that, the most I was able to do is change the background to transparent.

**Comment by Arashiryuu** [comment]
You're not supposed to edit the plugin file. I'd recommend using this custom css snippet and doing whatever changes you'd prefer with it from there.

```css
#app-mount #MemberCount {
  background: transparent;
}

#app-mount #MemberCount h2 {
  color: red;
}
```
