### ISSUE TITLE
[MemberCount] Wasted space under member count

### ISSUE THREAD

**Issue by jinai** [Arashiryuu/crap#166]
Hi,
Thanks for adding customization with the last update. My main gripe now is that there's a bit too much space under the member count.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Old&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;New
![image](https://user-images.githubusercontent.com/7669687/151688292-17138ee1-ed3b-43a1-abb2-6b1458ed044c.png)

Obviously the overflow fix is nice but while we're at it, I'm not sure I like the separator line extending the whole way across. It feels too enclosed maybe? See how they did the different sections in User Settings, still gives plenty of space around it. Could look like this:

![image](https://user-images.githubusercontent.com/7669687/151689976-923cf90c-43c3-48b1-91c1-4c1456098dfa.png)
I also made the separator slightly brighter to match the ones found in User Settings (hex is `#3B3D42`).

Thoughts?

In any case, appreciate the work. Thanks.

**Comment by jinai** [comment]
There's also the option of making it toggleable now that we have settings. Up to you, maybe that's too finicky.

**Comment by Arashiryuu** [comment]
As for the separator, you could use some custom css to restyle that, something like;
```css
div#MemberCount {
    border-bottom: 0;
}

div#MemberCount::after {
    content: '';
    display: block;
    position: absolute;
    bottom: 0;
    left: 10%;
    height: 100%;
    width: 80%;
    border-bottom: 2px solid hsla(0, 0%, 100%, 0.04);
}
```
seems decent
